[workspace]
resolver = "2"
members = ["crates/yajl", "crates/yajl-clib", "examples/yajl_test"]

[workspace.package]
edition = "2021"
version = "0.1.0"

[workspace.dependencies]
yajl = { path = "crates/yajl" }
yajl-clib = { path = "crates/yajl-clib" }

# external crates
libc = "0.2"
