[package]
name = "yajl_test"
edition.workspace = true
version.workspace = true

[dependencies]
yajl = { workspace = true }
# yajl-clib = { workspace = true }
libc = { workspace = true }
gpoint = "0.2.1"
